# 010baa3c577b1b60209a6f3c4273192d99a5a118c02ba3fc56a9946e999dcbf2
# Dockerfile generated by Maru 0.1.1

# Staged build using builder container
FROM janeliascicomp/builder:1.2.1 as builder
ARG GIT_TAG=main

# Checkout and build the code
WORKDIR /tmp/app
RUN git clone --branch $GIT_TAG --depth 1 https://github.com/JaneliaSciComp/ExM-pipeline.git . \
    && /usr/local/bin/buildinfo.sh 

# Create final image
FROM janeliascicomp/fiji:fiji-openjdk-8

COPY --from=builder /buildinfo /
COPY --from=builder /tmp/app/*/Fiji_plugins /opt/fiji/Fiji.app/plugins
COPY --from=builder /tmp/app/*/*.ijm /opt/fiji/Fiji.app/macros

ENTRYPOINT [ "/opt/fiji/entrypoint.sh", "--headless", "-macro" ]
CMD [ "Mask_connectionGPU.ijm" ]

